In [1]:
import torch
import numpy as np

# 从列表创建张量
a=[1,2,3.]
b=torch.tensor(a) 
print(type(b)) # <class 'torch.Tensor'>
print(b.dtype)  # torch.float32

# 从numpy数组创建张量
a=np.random.normal((2,3))
b=torch.tensor(a) 
print(b) # tensor([2.2654, 2.8027], dtype=torch.float64)

# 从张量创建张量
c=torch.ones_like(b) #创建与b形状相同的全1张量
print(c) # tensor([1., 1.], dtype=torch.float64)
c=torch.zeros_like(b) #创建与b形状相同的全0张量
print(c) # tensor([0., 0.], dtype=torch.float64)
c=torch.rand_like(b) #创建与b形状相同的随机张量
# print(c)  # tensor([0.4036, 0.9059], dtype=torch.float64)

# 从指定形状创建随机张量(元组和列表)
print(torch.rand((2,2)))
print(torch.ones([2,2]))
print(torch.zeros([2,2]))

<class 'torch.Tensor'>
torch.float32
tensor([-0.0335,  3.0265], dtype=torch.float64)
tensor([1., 1.], dtype=torch.float64)
tensor([0., 0.], dtype=torch.float64)
tensor([[0.7512, 0.1036],
        [0.0156, 0.0017]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [2]:
# 张量的属性
a = torch.rand((1, 2))
print(a.dtype)  # torch.float32
print(a.shape)  # torch.Size([1, 2])
print(a.device)  # cpu

torch.float32
torch.Size([1, 2])
cpu


In [27]:
# 张量的操作

print(torch.is_tensor(a))  # True
print(torch.is_complex(a))  # False
print(torch.is_floating_point(a))  # True

a=torch.tensor(1.)
print(torch.is_nonzero(a))  # True
print(torch.is_nonzero(torch.tensor(0.)))  # False
print(torch.numel(torch.rand((4,4)))) # 16，返回张量元素个数
print(torch.arange(5))  # tensor([0, 1, 2, 3, 4])
print(torch.arange(0,5,2)) # tensor([0, 2, 4])
print(torch.eye(3)) # 创建单位矩阵
print(torch.eye(3,2)) # 创建3x2的单位矩阵
print(torch.full((2,2),5)) # 创建2x2的全5张量
print(torch.full_like(b,5)) # 创建与b形状相同的全5张量
a=torch.rand((2,2))
b=torch.rand((2,3))
print(torch.cat((a,b),dim=1)) # 按列拼接(第二个维度，下标从0开始)，要求其余维度相同
a=torch.rand((2,2))
b=torch.rand((3,2))
print(torch.cat((a,b),dim=0)) # 按行拼接(第一个维度，下标从0开始)，要求其余维度相同

a=torch.rand((3,2))
print(torch.chunk(a,chunks=2)) #将张量按行分割为2块
b,c=torch.chunk(a,chunks=2,dim=1) #将张量按列分割为2块
print(b)
print(c)

# output[i][j][k]=input[index[i][j][k]][j][k] if dim=0
# output[i][j][k]=input[i][index[i][j][k]][k] if dim=1
# output[i][j][k]=input[i][j][index[i][j][k]] if dim=2
t=torch.tensor([[1,2],[3,4]])
print(torch.gather(t,1,torch.tensor([[0,0],[1,0]]))) # tensor([[1, 1],[4, 3]])
print(torch.gather(t,0,torch.tensor([[0,0],[1,0]]))) # tensor([[1, 2],[3, 2]])

a=torch.arange(0,4)
print(torch.reshape(a,(2,2))) # tensor([[0, 1],[2, 3]])
print(torch.reshape(a,[-1])) # tensor([0, 1, 2, 3])，-1表示变成一维张量

# self[index[i][j][k]][j][k] (+)= src[i][j][k] if dim=0
# self[i][index[i][j][k]][k] (+)= src[i][j][k] if dim=1
# self[i][j][index[i][j][k]] (+)= src[i][j][k] if dim=2
src=torch.arange(1,11).reshape((2,5))
print(src)
index=torch.tensor([[0,1,2,0]])
print(torch.zeros(3,5,dtype=src.dtype).scatter_(0,index,src)) # tensor([[1, 0, 0, 4, 0],[0, 2, 0, 0, 0],[0, 0, 3, 0, 0]])
print(torch.ones(3,5,dtype=src.dtype).scatter_add_(0,index,src)) # tensor([[2, 1, 1, 5, 1],[1, 3, 1, 1, 1],[1, 1, 4, 1, 1]])

a=torch.arange(10).reshape(5,2)
print(torch.split(a,2)) # 按行每2个元素分割一次
print(torch.split(a,[1,4])) # 按行分割为1和4两部分

print(torch.squeeze(torch.reshape(a,[5,1,2]))) # 去掉维度为1的维度
print(torch.squeeze(torch.reshape(a,[5,1,2,1,1]),dim=1))  # 去掉指定维度为1的维度

a=torch.rand([3,2])
b=torch.rand([3,2])
print(torch.stack((a,b),dim=0))
print(torch.stack((a,b)).shape) # torch.Size([2, 3, 2])
print(torch.stack((a,b),dim=1).shape) # torch.Size([3, 2, 2])

True
False
True
True
False
16
tensor([0, 1, 2, 3, 4])
tensor([0, 2, 4])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])
tensor([[5, 5],
        [5, 5]])
tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])
tensor([[0.6468, 0.6278, 0.3850, 0.3910, 0.0236],
        [0.1996, 0.9392, 0.0486, 0.6177, 0.5444]])
tensor([[0.0056, 0.6860],
        [0.0891, 0.5708],
        [0.8689, 0.3571],
        [0.5334, 0.4560],
        [0.7734, 0.2122]])
(tensor([[0.6968, 0.8361],
        [0.7605, 0.7571]]), tensor([[0.7564, 0.5738]]))
tensor([[0.6968],
        [0.7605],
        [0.7564]])
tensor([[0.8361],
        [0.7571],
        [0.5738]])
tensor([[1, 1],
        [4, 3]])
tensor([[1, 2],
        [3, 2]])
tensor([[0, 1],
        [2, 3]])
tensor([0, 1, 2, 3])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])
tensor([[2, 1, 1, 5, 1],
        [1,

In [67]:
# 张量的操作

src=torch.arange(6).reshape(2,3)
print(torch.take(src,torch.tensor([0,2,3]))) # 将张量展平后按索引取值

a=torch.tensor([1,2,3])
print(a.tile((2,))) # tensor([1, 2, 3, 1, 2, 3])，在指定维度上复制张量
b=torch.tensor([[1,2,3],[4,5,6]])
print(b.tile((2,2)))
# tensor([[1, 2, 3, 1, 2, 3],
#        [4, 5, 6, 4, 5, 6],
#        [1, 2, 3, 1, 2, 3],
#        [4, 5, 6, 4, 5, 6]])

print(torch.transpose(b,0,1)) # 转置指定维度

print(torch.unbind(b,dim=0)) # 按行拆分张量，返回元组
print(torch.unbind(b,dim=1)) # 按列拆分张量，返回元组

a=torch.rand([2,3,4])
print(a.shape) # torch.Size([2, 3, 4])
print(torch.unsqueeze(a, dim=0).shape) # torch.Size([1, 2, 3, 4])，在指定维度上增加维度
print(torch.unsqueeze(a, dim=1).shape) # torch.Size([2, 1, 3, 4])
print(torch.unsqueeze(a, dim=-1).shape) # torch.Size([2, 3, 4, 1])

a=torch.rand((2,2))
b=torch.ones_like(a)
print(torch.where(a<0.5,a,b)) # 小于0.5的元素保留，否则替换为b中对应位置的元素

#torch.manual_seed(0) # 设置随机种子

a=torch.empty(3,3).uniform_(0,1) # 生成0-1的随机概率
print(a)
print(torch.bernoulli(a)) # 根据概率生成伯努利分布的随机张量

print(torch.normal(2,3,size=(1,4))) # 生成均值为2，标准差为3的正态分布随机张量，大小为1x4

print(torch.randint(0,7,(2,2))) # 生成0-9的随机整数张量
print(torch.randn(3,4)) # 生成标准正态分布随机张量
print(torch.randperm(5)) # 生成0-4的随机排列

tensor([0, 2, 3])
tensor([1, 2, 3, 1, 2, 3])
tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
(tensor([1, 2, 3]), tensor([4, 5, 6]))
(tensor([1, 4]), tensor([2, 5]), tensor([3, 6]))
torch.Size([2, 3, 4])
torch.Size([1, 2, 3, 4])
torch.Size([2, 1, 3, 4])
torch.Size([2, 3, 4, 1])
tensor([[0.3390, 1.0000],
        [1.0000, 0.0165]])
tensor([[0.8615, 0.0865, 0.5069],
        [0.4150, 0.2367, 0.5661],
        [0.9135, 0.3538, 0.2032]])
tensor([[1., 1., 0.],
        [1., 1., 1.],
        [1., 0., 0.]])
tensor([[-3.9117,  3.8843,  1.6605,  3.3893]])
tensor([[3, 5],
        [5, 0]])
tensor([[-1.2535, -0.0592,  1.1878,  1.2247],
        [-0.8521, -1.1941,  1.1076,  0.6578],
        [-0.0423,  0.4580,  0.1448, -1.4195]])
tensor([1, 0, 4, 3, 2])
