In [16]:
import torch
import numpy as np

# 从列表创建张量
a=[1,2,3.]
b=torch.tensor(a) 
print(type(b)) # <class 'torch.Tensor'>
print(b.dtype)  # torch.float32

# 从numpy数组创建张量
a=np.random.normal((2,3))
b=torch.tensor(a) 
print(b) # tensor([2.2654, 2.8027], dtype=torch.float64)

# 从张量创建张量
c=torch.ones_like(b) #创建与b形状相同的全1张量
print(c) # tensor([1., 1.], dtype=torch.float64)
c=torch.zeros_like(b) #创建与b形状相同的全0张量
print(c) # tensor([0., 0.], dtype=torch.float64)
c=torch.rand_like(b) #创建与b形状相同的随机张量
# print(c)  # tensor([0.4036, 0.9059], dtype=torch.float64)

# 从指定形状创建随机张量(元组和列表)
print(torch.rand((2,2)))
print(torch.ones([2,2]))
print(torch.zeros([2,2]))

torch.float32
torch.Size([1, 2])
cpu


In [17]:
# 张量的属性
a = torch.rand((1, 2))
print(a.dtype)  # torch.float32
print(a.shape)  # torch.Size([1, 2])
print(a.device)  # cpu

torch.float32
torch.Size([1, 2])
cpu


In [60]:
# 张量的操作

print(torch.is_tensor(a))  # True
print(torch.is_complex(a))  # False
print(torch.is_floating_point(a))  # True

a=torch.tensor(1.)
print(torch.is_nonzero(a))  # True
print(torch.is_nonzero(torch.tensor(0.)))  # False
print(torch.numel(torch.rand((4,4)))) # 16，返回张量元素个数
print(torch.arange(5))  # tensor([0, 1, 2, 3, 4])
print(torch.arange(0,5,2)) # tensor([0, 2, 4])
print(torch.eye(3)) # 创建单位矩阵
print(torch.eye(3,2)) # 创建3x2的单位矩阵
print(torch.full((2,2),5)) # 创建2x2的全5张量
print(torch.full_like(b,5)) # 创建与b形状相同的全5张量
a=torch.rand((2,2))
b=torch.rand((2,3))
print(torch.cat((a,b),dim=1)) # 按列拼接(第二个维度，下标从0开始)，要求其余维度相同
a=torch.rand((2,2))
b=torch.rand((3,2))
print(torch.cat((a,b),dim=0)) # 按行拼接(第一个维度，下标从0开始)，要求其余维度相同

a=torch.rand((3,2))
print(torch.chunk(a,chunks=2)) #将张量按行分割为2块
b,c=torch.chunk(a,chunks=2,dim=1) #将张量按列分割为2块
print(b)
print(c)

# output[i][j][k]=input[index[i][j][k]][j][k] if dim=0
# output[i][j][k]=input[i][index[i][j][k]][k] if dim=1
# output[i][j][k]=input[i][j][index[i][j][k]] if dim=2
t=torch.tensor([[1,2],[3,4]])
print(torch.gather(t,1,torch.tensor([[0,0],[1,0]]))) # tensor([[1, 1],[4, 3]])
print(torch.gather(t,0,torch.tensor([[0,0],[1,0]]))) # tensor([[1, 2],[3, 2]])

a=torch.arange(0,4)
print(torch.reshape(a,(2,2))) # tensor([[0, 1],[2, 3]])
print(torch.reshape(a,[-1])) # tensor([0, 1, 2, 3])，-1表示变成一维张量

# self[index[i][j][k]][j][k] (+)= src[i][j][k] if dim=0
# self[i][index[i][j][k]][k] (+)= src[i][j][k] if dim=1
# self[i][j][index[i][j][k]] (+)= src[i][j][k] if dim=2
src=torch.arange(1,11).reshape((2,5))
print(src)
index=torch.tensor([[0,1,2,0]])
print(torch.zeros(3,5,dtype=src.dtype).scatter_(0,index,src)) # tensor([[1, 0, 0, 4, 0],[0, 2, 0, 0, 0],[0, 0, 3, 0, 0]])
print(torch.ones(3,5,dtype=src.dtype).scatter_add_(0,index,src)) # tensor([[2, 1, 1, 5, 1],[1, 3, 1, 1, 1],[1, 1, 4, 1, 1]])

True
False
False
True
False
16
tensor([0, 1, 2, 3, 4])
tensor([0, 2, 4])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])
tensor([[5, 5],
        [5, 5]])
tensor([[5.],
        [5.],
        [5.]])
tensor([[0.0490, 0.1011, 0.8945, 0.8467, 0.6789],
        [0.3001, 0.9983, 0.9483, 0.9997, 0.0160]])
tensor([[0.5864, 0.7532],
        [0.1382, 0.6743],
        [0.0912, 0.3669],
        [0.3023, 0.8548],
        [0.1923, 0.7357]])
(tensor([[0.6349, 0.4103],
        [0.4556, 0.7916]]), tensor([[0.1846, 0.2449]]))
tensor([[0.6349],
        [0.4556],
        [0.1846]])
tensor([[0.4103],
        [0.7916],
        [0.2449]])
tensor([[1, 1],
        [4, 3]])
tensor([[1, 2],
        [3, 2]])
tensor([[0, 1],
        [2, 3]])
tensor([0, 1, 2, 3])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])
tensor([[2, 1, 1, 5, 1],
        [1, 3, 1, 1, 1